export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';
export const STORE_CLEAR = 'STORE_CLEAR';

export const CHECK_STORAGE = 'CHECK_STORAGE';

export const CHANGE_NAME = 'CHANGE_NAME';

export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';

export const REGISTRATION_USER_START = 'REGISTRATION_USER_START';
export const REGISTRATION_USER_SUCCESS = 'REGISTRATION_USER_SUCCESS';
export const REGISTRATION_USER_FAIL = 'REGISTRATION_USER_FAIL';

export const ADD_NEW_ITEM_START = 'ADD_NEW_ITEM_START';
export const ADD_NEW_ITEM_SUCCESS = 'ADD_NEW_ITEM_SUCCESS';
export const ADD_NEW_ITEM_FAIL = 'ADD_NEW_ITEM_FAIL';

export const REQUEST_CONTENT_START = 'REQUEST_CONTENT_START';
export const REQUEST_CONTENT_SUCCESS = 'REQUEST_CONTENT_SUCCESS';
export const REQUEST_CONTENT_FAIL = 'REQUEST_CONTENT_FAIL';

export const SAVE_ITEM_START = 'SAVE_ITEM_START';
export const SAVE_ITEM_SUCCESS = 'SAVE_ITEM_SUCCESS';
export const SAVE_ITEM_FAIL = 'SAVE_ITEM_FAIL';

export const REMOVE_ITEM_START = 'REMOVE_ITEM_START';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL';


export const CHECK_WIN = 'CHECK_WIN';
export const ON_SUBMIT = 'ON_SUBMIT';
export const HOW_MANY_CORRECT = 'HOW_MANY_CORRECT';
export const RESTART_GAME = 'RESTART_GAME';
export const PICK_UP_COLOR = 'PICK_UP_COLOR';
export const ON_REMOVE_COLOR = 'ON_REMOVE_COLOR';